# docker-compose.yml
version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: integration_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: integration_db
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: integration_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongo_data:
